import { useState } from 'react'
import { BellIcon, ChatCircleTextIcon, CheckCircleIcon, DesktopIcon, DownloadSimpleIcon, EnvelopeIcon, InfoIcon, KeyIcon, LockKeyIcon, MoonIcon, PaintBrushIcon, ShieldCheckIcon, SignOutIcon, SlidersHorizontalIcon, SunIcon, TrashIcon, UserCircleIcon } from '@phosphor-icons/react'
import { GlassSheet, MenuRow, PageTitle, Toggle } from './GlassUI'
import { validateAuth, validateFeedback } from './glassModel'
import avatar from './assets/avatar.png'
import logo from '../../logo.png'
import type { Preferences } from './preferences'

type View = 'root'|'account'|'privacy'|'theme'|'feedback'|'notifications'|'devices'|'about'|'auth'|'home'
export type FeedbackTicket = {id:string;text:string;category:string}
type Props = {initialView?:View;embeddedTab?:boolean;prefs:Preferences;setPrefs:(p:Preferences)=>void;user:string|null;setUser:(s:string|null)=>void;back:()=>void;notify:(s:string)=>void;exportData:()=>void;tickets:FeedbackTicket[];setTickets:React.Dispatch<React.SetStateAction<FeedbackTicket[]>>}

export function AccountCenter({initialView='root',embeddedTab=false,prefs,setPrefs,user,setUser,back,notify,exportData,tickets,setTickets}:Props) {
  const [view,setView]=useState<View>(initialView)
  const [signup,setSignup]=useState(false)
  const [identifier,setIdentifier]=useState('')
  const [code,setCode]=useState('')
  const [sent,setSent]=useState(false)
  const [consent,setConsent]=useState(false)
  const [authError,setAuthError]=useState('')
  const [nickname,setNickname]=useState(user??'')
  const [feedback,setFeedback]=useState('')
  const [category,setCategory]=useState('功能建议')
  const [diagnostics,setDiagnostics]=useState(false)
  const [confirm,setConfirm]=useState<'logout'|'delete'|'device'|null>(null)
  const [confirmation,setConfirmation]=useState('')
  const [deviceBound,setDeviceBound]=useState(true)
  const change=<K extends keyof Preferences>(key:K,value:Preferences[K])=>setPrefs({...prefs,[key]:value})
  const labels:Record<View,string>={root:'个人中心',account:'账号管理',privacy:'隐私与数据',theme:'主题与动效',feedback:'帮助与反馈',notifications:'通知偏好',devices:'设备与授权',about:'关于刻迹',auth:signup?'创建账号':'欢迎回来',home:'首页显示内容'}
  function login() {
    const error=validateAuth(identifier,code,consent)
    if(error){setAuthError(error==='consent'?'请先阅读并勾选协议确认':error==='identifier'?'请输入有效的邮箱或手机号':'请输入演示验证码 246810');return}
    const name=signup&&nickname.trim()?nickname.trim():'Joey'
    setUser(name);setNickname(name);setIdentifier('');setCode('');setAuthError('');setView('root');notify(signup?'演示注册完成，已进入个人工作台':'演示登录成功，游客记录保留在本次预览中')
  }
  return <section className="gl-settings gl-enter" key={view}>
    <PageTitle title={embeddedTab&&view==='root'?'我的':labels[view]} back={embeddedTab&&view==='root'?undefined:()=>view==='root'?back():setView('root')} subtitle={view==='root'?'让刻迹，更像你的工作方式。':undefined}/>
    {view==='root'&&<><button className="gl-profile-card" onClick={()=>setView(user?'account':'auth')}><img src={avatar} alt="演示头像"/><div><h2>{user??'以你的节奏开始'}</h2><p>{user?'个人工作台 · 演示账号':'登录或注册，连接你的工作台'}</p></div><UserCircleIcon size={24}/></button><div className="gl-group">
      <MenuRow icon={<UserCircleIcon/>} title="账号管理" detail={user?'个人资料、退出与注销':'登录 / 注册 / 游客体验'} onClick={()=>setView(user?'account':'auth')}/>
      <MenuRow icon={<DesktopIcon/>} title="设备与授权" detail="电脑 Runner 与 AI 账号绑定" onClick={()=>setView('devices')}/>
      <MenuRow icon={<ShieldCheckIcon/>} title="隐私与数据" detail="同步、数据使用与导出" onClick={()=>setView('privacy')}/>
    </div><div className="gl-group">
      <MenuRow icon={<PaintBrushIcon/>} title="主题与动效" detail={prefs.theme==='light'?'冰晶白':prefs.theme==='dark'?'深海蓝':'跟随系统'} onClick={()=>setView('theme')}/>
      <MenuRow icon={<SlidersHorizontalIcon/>} title="首页显示内容" detail="选择想看见的协作信息" onClick={()=>setView('home')}/>
      <MenuRow icon={<BellIcon/>} title="通知偏好" detail="验收、恢复与免打扰" onClick={()=>setView('notifications')}/>
    </div><div className="gl-group"><MenuRow icon={<ChatCircleTextIcon/>} title="帮助与反馈" onClick={()=>setView('feedback')}/><MenuRow icon={<InfoIcon/>} title="关于刻迹" detail="设计预览 v0.2" onClick={()=>setView('about')}/></div><p className="gl-fine">当前是交互设计预览，不连接真实账户或 AI。<br/>仅主题与显示偏好保存在本浏览器。</p></>}
    {view==='account'&&<><div className="gl-profile-card"><img src={avatar} alt="演示头像"/><div><h2>{user??'游客'}</h2><p>个人账号 · 验证码登录</p></div></div><form onSubmit={e=>{e.preventDefault();if(nickname.trim()){setUser(nickname.trim());notify('演示昵称已更新')}}} className="gl-form"><label>昵称<input value={nickname} onChange={e=>setNickname(e.target.value)} maxLength={24} required placeholder="你的名字"/></label><button className="gl-primary" type="submit">保存资料</button></form><div className="gl-group"><MenuRow icon={<EnvelopeIcon/>} title="登录方式" detail="邮箱 / 手机验证码 · 演示绑定" onClick={()=>{setView('auth');setSignup(false)}}/><MenuRow icon={<KeyIcon/>} title="登录设备" detail="查看并撤销设备授权" onClick={()=>setView('devices')}/><MenuRow icon={<SignOutIcon/>} title="退出登录" onClick={()=>setConfirm('logout')}/></div><button className="gl-danger" onClick={()=>{setConfirmation('');setConfirm('delete')}}><TrashIcon size={18}/>注销账号</button><p className="gl-fine">生产版注销需再次验证身份并说明数据保留规则；这里仅演示确认流程。</p></>}
    {view==='auth'&&<><div className="gl-auth-symbol"><img src={logo} alt="刻迹"/></div><p className="gl-auth-intro">让个人与 AI 的每一次协作，<br/>都走向真正的交付。</p><div className="gl-segments"><button className={!signup?'active':''} onClick={()=>setSignup(false)}>登录</button><button className={signup?'active':''} onClick={()=>setSignup(true)}>注册</button></div><form className="gl-form" onSubmit={e=>{e.preventDefault();login()}}>
      {signup&&<label>昵称<input value={nickname} onChange={e=>setNickname(e.target.value)} placeholder="怎么称呼你" maxLength={24}/></label>}
      <label>邮箱 / 手机号<input autoComplete="off" value={identifier} onChange={e=>setIdentifier(e.target.value)} placeholder="例如 joey@example.com"/></label><label>演示验证码<div className="gl-input-action"><input inputMode="numeric" autoComplete="off" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} placeholder="6 位验证码"/><button type="button" onClick={()=>{setSent(true);setAuthError('')}}>{sent?'再次显示':'获取验证码'}</button></div></label>{sent&&<p className="gl-info">演示验证码：<b>246810</b>。不会发送短信或邮件，请勿输入真实验证码。</p>}
      <label className="gl-checkbox"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>我已阅读并同意演示版使用条款与隐私说明</span></label><button className="gl-link" type="button" onClick={()=>setView('about')}>查看使用与隐私说明</button>{authError&&<p role="alert" className="gl-error">{authError}</p>}<button className="gl-primary" type="submit">{signup?'创建演示账号':'登录演示账号'}</button><button className="gl-secondary" type="button" onClick={()=>{setUser(null);back()}}>先体验，暂不登录</button></form><p className="gl-fine">本页为交互演示。输入不会上传或存入本地存储；登录后保留本次游客演示记录。</p></>}
    {view==='privacy'&&<><div className="gl-info"><ShieldCheckIcon size={24}/><div><b>数据边界，看得清楚。</b><p>产品设计：代码与 CLI 凭据留在电脑；云端协调计划、状态与报告。</p></div></div><div className="gl-group"><Toggle label="云端同步" detail="项目、任务、Plan 与执行状态" checked={prefs.sync} change={v=>change('sync',v)}/><Toggle label="分享脱敏诊断" detail="默认关闭；反馈时仍需逐次选择" checked={prefs.shareLogs} change={v=>change('shareLogs',v)}/></div><div className="gl-data-map"><h3>哪些信息会交给 AI？</h3><p>仅派发时确认的 Plan 描述、选定仓库及允许访问的上下文。具体工具的数据条款应在授权页查看。</p><h3>哪些信息不应上传？</h3><p>CLI 登录凭据、API Key、环境变量中的秘密。日志需脱敏；不承诺未经验证的端到端加密。</p></div><button className="gl-secondary" onClick={exportData}><DownloadSimpleIcon size={18}/>导出演示数据</button><button className="gl-danger" onClick={()=>{setView('account')}}>管理账号注销</button><p className="gl-fine">这些开关用于评审偏好交互，不改变现有生产上传行为。正式隐私政策需与实际采集、留存及第三方处理一致。</p></>}
    {view==='theme'&&<><p className="gl-body-copy">清晨或深夜，都有舒适的工作界面。</p><div className="gl-theme-options">{([{id:'light',label:'冰晶白',Icon:SunIcon},{id:'dark',label:'深海蓝',Icon:MoonIcon},{id:'system',label:'跟随系统',Icon:DesktopIcon}] as const).map(t=><button key={t.id} className={prefs.theme===t.id?'active':''} aria-pressed={prefs.theme===t.id} onClick={()=>change('theme',t.id)}><t.Icon size={28} weight="duotone"/><b>{t.label}</b>{prefs.theme===t.id&&<CheckCircleIcon size={17} weight="fill"/>}</button>)}</div><h3 className="gl-section-label">强调色</h3><div className="gl-segments"><button className={prefs.accent==='blue'?'active':''} onClick={()=>change('accent','blue')}>冰蓝</button><button className={prefs.accent==='violet'?'active':''} onClick={()=>change('accent','violet')}>鸢紫</button></div><div className="gl-group"><Toggle label="减少动态效果" detail="关闭进场、浮动与脉冲，保留状态反馈" checked={prefs.reduceMotion} change={v=>change('reduceMotion',v)}/></div><p className="gl-fine">也会尊重系统的“减少动态效果”偏好。主题与显示设置保存在此浏览器。</p></>}
    {view==='home'&&<><p className="gl-body-copy">保留目标和下一步行动，其余由你选择。</p><div className="gl-group"><Toggle label="人机协作详情" detail="我与 AI 的分工和接续状态" checked={prefs.showFlow} change={v=>change('showFlow',v)}/><Toggle label="工具额度摘要" detail="首页显示 Codex / Claude 状态" checked={prefs.showTools} change={v=>change('showTools',v)}/><Toggle label="每日寄语" detail="首页底部的雪山卡片" checked={prefs.showQuote} change={v=>change('showQuote',v)}/></div><div className="gl-info">需要你处理的验收、授权或额度阻塞不会因隐藏模块而消失。</div></>}
    {view==='notifications'&&<><div className="gl-group"><Toggle label="工作通知" detail="Plan 完成、待验收与执行异常" checked={prefs.notifications} change={v=>change('notifications',v)}/><Toggle label="夜间免打扰" detail="22:00–08:00 · Asia/Dubai" checked={prefs.quiet} change={v=>change('quiet',v)}/><Toggle label="自然恢复后自动续跑" detail="原会话、可用订阅额度、零额外付费" checked={prefs.autoResume} change={v=>change('autoResume',v)}/></div><p className="gl-fine">此预览不请求系统通知权限。生产版需要单独授权；电脑离线时无法执行本机任务。</p></>}
    {view==='devices'&&<><div className="gl-group"><MenuRow icon={<DesktopIcon/>} title="MacBook Pro" detail="当前 Runner · 在线 · 演示" onClick={()=>notify('工作目录：TimeTrace · 单编码进程 · 演示设备')}/><MenuRow icon={<DesktopIcon/>} title="Mac mini" detail={deviceBound?'Valley · Claude 个人账号 · 已绑定':'授权已撤销 · 演示'} onClick={()=>deviceBound?setConfirm('device'):notify('此演示设备已经撤销授权')}/></div><div className="gl-info"><LockKeyIcon size={24}/><p>刻迹账号绑定 Runner；Runner 内的工具配置绑定本机 CLI 账号。凭据不发送到手机，撤销后停止新的派发。</p></div><button className="gl-secondary" onClick={()=>notify('生产版：在电脑运行 keji agent login，用一次性设备码完成绑定。当前不连接真实电脑。')}>如何连接新电脑</button></>}
    {view==='feedback'&&<><details className="gl-faq"><summary>额度到了恢复时间，为什么还没运行？</summary><p>短时窗口恢复后仍需检查周额度、电脑在线、登录与授权状态。“预计恢复”不等于已经可用。</p></details><details className="gl-faq"><summary>自动续跑会额外收费吗？</summary><p>设计要求只使用现有订阅；无法验证计费边界时不自动执行，不购买额度或调用付费回退。</p></details><form className="gl-form" onSubmit={e=>{e.preventDefault();if(!validateFeedback(feedback)){notify('请填写 10–1000 字的具体问题或建议');return}setTickets(t=>[{id:`FB-${String(t.length+1).padStart(3,'0')}`,text:feedback.trim(),category},...t]);setFeedback('');notify('反馈已记录在本次预览，未发送给真实客服')}}><label>反馈类型<select value={category} onChange={e=>setCategory(e.target.value)}><option>功能建议</option><option>体验问题</option><option>错误报告</option></select></label><label>描述<textarea value={feedback} onChange={e=>setFeedback(e.target.value)} minLength={10} maxLength={1000} required placeholder="发生了什么？你期望怎样改进？"/></label><label className="gl-checkbox"><input type="checkbox" checked={diagnostics} onChange={e=>setDiagnostics(e.target.checked)}/><span>附带演示诊断信息（不读取真实日志）</span></label>{diagnostics&&<p className="gl-info">附件预览：设计版本 v0.2、当前主题、页面名称。不含账号、代码或设备标识。</p>}<button className="gl-primary">记录反馈</button></form>{tickets.length>0&&<><h3 className="gl-section-label">本次反馈</h3>{tickets.map(t=><article className="gl-ticket" key={t.id}><b>{t.id} · {t.category}</b><span>已记录 · 演示</span><p>{t.text}</p></article>)}</>}</>}
    {view==='about'&&<><div className="gl-about"><img src={logo} alt="刻迹 Logo"/><h2>刻迹</h2><p>个人与 AI 的多项目工作台</p><small>交互设计预览 v0.2 · 2026.09</small></div><div className="gl-data-map"><h3>演示使用说明</h3><p>所有项目、账号、额度与报告均为示例，不连接真实 AI，不产生付费。登录字段不会上传。设置偏好保存在浏览器，工作记录刷新后恢复。</p><h3>隐私说明</h3><p>本预览不是正式隐私政策。生产版将明确采集范围、保留时间、数据删除、第三方处理和用户权利。</p></div><button className="gl-secondary" onClick={()=>setView('feedback')}>联系与反馈</button></>}
    {confirm&&<GlassSheet title={confirm==='logout'?'退出登录？':confirm==='device'?'撤销设备授权？':'注销演示账号？'} close={()=>setConfirm(null)}><p className="gl-body-copy">{confirm==='logout'?'退出后回到游客体验。本次示例项目保留，不影响任何真实账号。':confirm==='device'?'演示 Mac mini 将不再接收新的派发。实际运行任务需另行停止。':'仅清除本次演示登录资料，项目示例保留。不会删除生产数据。请输入“注销”确认。'}</p>{confirm==='delete'&&<label className="gl-form">确认文字<input aria-label="注销确认文字" value={confirmation} onChange={e=>setConfirmation(e.target.value)} placeholder="输入 注销"/></label>}<button className="gl-danger" disabled={confirm==='delete'&&confirmation!=='注销'} onClick={()=>{if(confirm==='device')setDeviceBound(false);else {setUser(null);setNickname('');setView('root')}setConfirm(null);notify('演示操作完成，未修改任何真实账号或授权')}}>确认{confirm==='logout'?'退出':confirm==='device'?'撤销':'注销'}</button><button className="gl-secondary" onClick={()=>setConfirm(null)}>取消</button></GlassSheet>}
  </section>
}
