import { useEffect, useRef, useState } from 'react'
import { ArrowRightIcon, ArrowsClockwiseIcon, AsteriskSimpleIcon, ChartBarIcon, CheckCircleIcon, CheckIcon, CircleIcon, ClockIcon, CodeIcon, DownloadSimpleIcon, FileTextIcon, FolderIcon, GearSixIcon, GitBranchIcon, HourglassIcon, OpenAiLogoIcon, PauseIcon, PlayIcon, PlusIcon, ShieldCheckIcon, SparkleIcon, SquaresFourIcon, UserIcon } from '@phosphor-icons/react'
import type { Icon } from '@phosphor-icons/react'
import { AccountCenter } from './AccountCenter'
import type { FeedbackTicket } from './AccountCenter'
import { defaultPreferences } from './preferences'
import type { Preferences } from './preferences'
import { Empty, GlassSheet, PageTitle, Toggle } from './GlassUI'
import { initialGlassState, restoreQuota, transitionPlan } from './glassModel'
import type { GlassPlan, Status } from './glassModel'
import hero from './assets/glass-hero.png'
import mountains from './assets/mountain-banner.png'
import ribbon from './assets/collaboration-ribbon.png'
import { plansForReport } from './reportScope'
import logo from '../../logo.png'
import './glass.css'

type Tab = 'today'|'projects'|'timeline'|'ai'|'mine'|'reports'
type Project = {id:string;name:string;goal:string;date:string}
type Task = {id:string;projectId:string;title:string;priority:number}
const tabs:{id:Tab;title:string;icon:Icon}[]=[{id:'today',title:'今日',icon:SquaresFourIcon},{id:'projects',title:'项目',icon:FolderIcon},{id:'timeline',title:'时间线',icon:GitBranchIcon},{id:'ai',title:'AI',icon:SparkleIcon},{id:'mine',title:'我的',icon:UserIcon}]
const statusText:Record<Status,string>={ready:'待执行',running:'执行中',waiting:'等待额度',review:'待验收',accepted:'已验收',cancelled:'已取消'}
const toolRows=[{name:'Codex',remaining:62,window:'短时窗口',detail:'周额度剩余 41%',reset:'17:30 后核验',capability:'可派发 · 可恢复'}, {name:'Claude Code',remaining:0,window:'短时窗口',detail:'周额度剩余 28%',reset:'14:30 后核验',capability:'可派发 · 可恢复'}, {name:'Cursor',remaining:34,window:'月度窗口',detail:'手动记录 · 不参与自动派发',reset:'9 月 22 日',capability:'记录 · 提醒'}, {name:'Gemini CLI',remaining:null,window:'额度未知',detail:'没有可信样本',reset:'恢复时间未知',capability:'记录 · 待适配'}]
function ToolIcon({name}:{name:string}) { return name==='Codex'?<OpenAiLogoIcon weight="regular"/>:name==='Claude Code'?<AsteriskSimpleIcon weight="bold"/>:<SparkleIcon weight="duotone"/> }
function loadPreferences():Preferences {
  try { const raw=JSON.parse(localStorage.getItem('keji-glass-preferences')??'null'); if(!raw||typeof raw!=='object')return defaultPreferences
    const p={...defaultPreferences}; for(const key of Object.keys(p) as (keyof Preferences)[]){if(typeof p[key]==='boolean'&&typeof raw[key]==='boolean')Object.assign(p,{[key]:raw[key]})}
    if(['light','dark','system'].includes(raw.theme))p.theme=raw.theme
    if(['blue','violet'].includes(raw.accent))p.accent=raw.accent
    return p
  }catch{return defaultPreferences}
}
export function GlassWorkspace() {
  const [tab,setTab]=useState<Tab>('today')
  const [reportOrigin,setReportOrigin]=useState<'today'|'projects'>('today')
  const [state,setState]=useState(initialGlassState)
  const [prefs,setPrefs]=useState(loadPreferences)
  const [systemDark,setSystemDark]=useState(()=>window.matchMedia('(prefers-color-scheme: dark)').matches)
  const [user,setUser]=useState<string|null>('Joey')
  const [tickets,setTickets]=useState<FeedbackTicket[]>([])
  const [settings,setSettings]=useState<'root'|'home'|null>(null)
  const [role,setRole]=useState<'human'|'ai'>('human')
  const [projects,setProjects]=useState<Project[]>([{id:'keji',name:'刻迹',goal:'v1.2 · 多 AI 工作台',date:'2026-09-18'},{id:'valley',name:'Valley',goal:'v2.4 · 远程执行稳定性',date:'2026-09-17'}])
  const [tasks,setTasks]=useState<Task[]>([{id:'t1',projectId:'keji',title:'多 AI 额度管理',priority:1},{id:'t2',projectId:'valley',title:'远程任务恢复',priority:2}])
  const [projectId,setProjectId]=useState<string|null>(null)
  const [taskId,setTaskId]=useState<string|null>(null)
  const [selected,setSelected]=useState<string|null>(null)
  const [checks,setChecks]=useState<string[]>([])
  const [policy,setPolicy]=useState('均衡')
  const [create,setCreate]=useState<'project'|'task'|'plan'|null>(null)
  const [info,setInfo]=useState<'score'|'evidence'|'demo'|null>(null)
  const [tool,setTool]=useState<string|null>(null)
  const [notice,setNotice]=useState('')
  const [weekBlocked,setWeekBlocked]=useState(false)
  const [timelineProject,setTimelineProject]=useState('all')
  const [timelineLane,setTimelineLane]=useState('all')
  const [weekView,setWeekView]=useState(false)
  const [day,setDay]=useState(14)
  const scroll=useRef<HTMLDivElement>(null)
  const currentPlan=state.plans.find(p=>p.id===selected)
  const project=projects.find(p=>p.id===projectId)
  const task=tasks.find(t=>t.id===taskId)
  const reportPlans=plansForReport(state.plans,tasks,tab==='reports'&&reportOrigin==='projects'?projectId:null)
  const reportProject=tab==='reports'&&reportOrigin==='projects'?project:undefined
  const activeTab=tab==='reports'?reportOrigin:tab
  const focusPlans=state.plans.filter(p=>p.taskId==='t1')
  const accepted=focusPlans.filter(p=>p.status==='accepted').length
  const pending=state.plans.find(p=>p.status==='review')
  const waiting=state.plans.find(p=>p.status==='waiting')
  const progress=focusPlans.length?accepted/focusPlans.length:0
  useEffect(()=>{try{localStorage.setItem('keji-glass-preferences',JSON.stringify(prefs))}catch{/* Private browsing may disallow preference storage. */}},[prefs])
  useEffect(()=>{const media=window.matchMedia('(prefers-color-scheme: dark)');const change=()=>setSystemDark(media.matches);media.addEventListener('change',change);return()=>media.removeEventListener('change',change)},[])
  useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),4200);return()=>clearTimeout(timer)},[notice])
  function navigate(next:Tab){setTab(next);setSettings(null);setProjectId(null);setTaskId(null);scroll.current?.scrollTo({top:0,behavior:'instant'})}
  function openReport(origin:'today'|'projects'){setReportOrigin(origin);setTab('reports');setSettings(null);scroll.current?.scrollTo(0,0)}
  function closeReport(){setTab(reportOrigin);scroll.current?.scrollTo(0,0)}
  function openPlan(p:GlassPlan){setChecks(p.status==='accepted'?p.criteria:[]);setSelected(p.id);setPolicy('均衡')}
  function act(action:'run'|'finish'|'accept'|'cancel') {
    if(!selected)return
    const result=transitionPlan(state,selected,action)
    if(result.error){setNotice(result.error==='dependencies'?'请先验收前置 Plan':'当前状态不能执行此操作');return}
    setState(result.state);setSelected(null);setNotice(action==='accept'?'验收已记录，目标与日报已更新':action==='cancel'?'Plan 已取消，不会自动续跑':'演示执行状态已更新')
  }
  function exportData(report=false){const text=report?`# ${reportProject?.name??'全部项目'}开发日报 · 2026-09-14\n\n演示数据，时区 Asia/Dubai。\n\n${reportPlans.map(p=>`- ${p.title}：${statusText[p.status]} / ${p.tool}`).join('\n')}\n\n没有真实费用和代码提交，所有证据为交互示例。`:JSON.stringify({demo:true,projects,tasks,plans:state.plans},null,2);const a=document.createElement('a');const url=URL.createObjectURL(new Blob([text],{type:report?'text/markdown':'application/json'}));a.href=url;a.download=report?'keji-demo-changelog.md':'keji-demo-data.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('已导出演示数据，不含账户或凭据')}
  function simulateQuota(){setState(s=>restoreQuota(s,weekBlocked,prefs.autoResume));setNotice(weekBlocked?'短时额度恢复，但周额度仍阻塞执行':prefs.autoResume?'核验通过：等待中的原会话已演示续跑':'已核验额度，自动续跑关闭，等待手动继续')}
  function createItem(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);const title=String(data.get('title')??'').trim();if(!title)return;const id=crypto.randomUUID();
    if(create==='project'){setProjects(p=>[...p,{id,name:title,goal:String(data.get('goal')??'新版本目标'),date:String(data.get('date')??'2026-09-18')}]);setProjectId(id);setTaskId(null)}
    if(create==='task'&&projectId){setTasks(t=>[...t,{id,projectId,title,priority:Number(data.get('priority'))}]);setTaskId(id)}
    if(create==='plan'&&taskId){setState(s=>({...s,plans:[...s.plans,{id,taskId,title,priority:Number(data.get('priority')),tool:String(data.get('tool')),status:'ready',depends:data.getAll('depends').map(String),criteria:String(data.get('criteria')).split('\n').map(c=>c.trim()).filter(Boolean)}]}))}
    setCreate(null);setNotice('已创建到本次预览，刷新后恢复示例数据')
  }
  return <div className="gl-stage"><aside className="gl-review-rail"><img src={logo} alt="刻迹 Logo"/><p>KEJI / DESIGN REVIEW</p><h1>把今天，<br/>交给更好的协作。</h1><span>个人与 AI 的多项目工作台</span><div>{tabs.map(t=><button key={t.id} className={activeTab===t.id&&!settings?'active':''} onClick={()=>navigate(t.id)}><t.icon size={18}/>{t.title}</button>)}<button onClick={()=>{setProjectId(null);openReport('today')}}><ChartBarIcon size={18}/>开发报告</button></div><small>冰晶白 · 交互设计稿<br/>工作状态为演示；不会调用真实 AI。</small><a href="/review-v1">上一版设计</a></aside>
    <div className="gl-app" data-theme={prefs.theme==='system'?(systemDark?'dark':'light'):prefs.theme} data-accent={prefs.accent} data-reduced-motion={prefs.reduceMotion}>
      <div className="gl-scroll" ref={scroll}>
        {settings||tab==='mine'?<AccountCenter key={settings??'mine'} initialView={settings??'root'} embeddedTab={tab==='mine'&&!settings} prefs={prefs} setPrefs={setPrefs} user={user} setUser={setUser} back={()=>{if(settings)setSettings(null);else navigate('today')}} notify={setNotice} exportData={()=>exportData()} tickets={tickets} setTickets={setTickets}/>:<main className="gl-main gl-enter" key={tab}>
        {tab==='today'&&<>
          <header className="gl-home-header"><div><h1>刻迹</h1><p>把今天，<br/>交给更好的协作。</p></div><div className="gl-header-actions"><div><button className="gl-report-entry" aria-label="开发报告" onClick={()=>openReport('today')}><ChartBarIcon size={24}/><span>报告</span></button><button className="gl-icon" aria-label="设置" onClick={()=>{setSettings('root');scroll.current?.scrollTo(0,0)}}><GearSixIcon size={25}/></button></div><button className="gl-demo-pill" onClick={()=>setInfo('demo')}>概念演示</button></div></header>
          <button className="gl-hero" onClick={()=>{navigate('projects');setProjectId('keji')}} aria-label="查看刻迹本周目标"><img src={hero} alt="冰蓝玻璃与流动光带"/><div className="gl-goal-copy"><span>本周目标</span><h2>刻迹 v1.2</h2><p>周五交付</p><b>{accepted} / {focusPlans.length} 已验收</b><div className="gl-goal-progress" role="progressbar" aria-label="本周目标进度" aria-valuenow={Math.round(progress*100)} aria-valuemin={0} aria-valuemax={100}>{focusPlans.map(p=><i key={p.id} className={p.status==='accepted'?'complete':''}/>)}</div></div><span className="gl-goal-motto">更少重复<br/>更大可能</span><span className="gl-hero-arrow"><ArrowRightIcon size={21}/></span></button>
          <div className="gl-role-switch" role="group" aria-label="关注执行者"><button aria-pressed={role==='human'} className={role==='human'?'active':''} onClick={()=>setRole('human')}><UserIcon size={25} weight="fill"/><span><b>我</b><small>负责验收与决策</small></span></button><button aria-pressed={role==='ai'} className={role==='ai'?'active':''} onClick={()=>setRole('ai')}><SparkleIcon size={27} weight="duotone"/><span><b>AI</b><small>负责验证与执行</small></span></button></div>
          {prefs.showFlow&&<div className="gl-collaboration"><button onClick={()=>pending?openPlan(pending):setNotice('当前没有待验收 Plan')}><span className="gl-orb"><CheckIcon weight="bold" size={23}/></span><div><b>我 · 验收</b><p>确认数据与结果</p><small>今天 10:24</small></div></button><img className="gl-flow-ribbon" src={ribbon} alt=""/><button onClick={()=>navigate('ai')}><span className="gl-orb soft"><ArrowsClockwiseIcon className="gl-spin" size={22}/></span><div><b>Codex · 验证</b><p>{pending?'结果待确认':'验证已完成'}</p><small>预计 5–10 分钟</small></div></button></div>}
          <div className="gl-primary-task"><span className="gl-file-art"><FileTextIcon size={32} weight="duotone"/></span><div><small>{role==='human'?'待你处理':'AI 工作状态'}</small><h2>{role==='human'?(pending?.title??'本轮验收已完成'):(waiting?.title??'所有执行有序推进')}</h2><p>{role==='human'?(pending?`由 ${pending.tool} 完成，等待你确认`:'继续规划下一步，让目标向前。'):(waiting?'额度恢复后，原会话继续':'查看各工具与后续安排')}</p></div><button className="gl-primary compact" onClick={()=>role==='human'&&pending?openPlan(pending):navigate(role==='human'?'projects':'ai')}>{role==='human'&&pending?'继续验收':'查看详情'}<ArrowRightIcon size={17}/></button></div>
          {!prefs.showTools&&waiting&&<button className="gl-essential" onClick={()=>navigate('ai')}><HourglassIcon size={18}/>Claude 等待额度 · 14:30 后核验<ArrowRightIcon/></button>}
          {prefs.showTools&&<><div className="gl-section-heading"><h2>工具状态</h2><button onClick={()=>navigate('ai')}>查看详情<ArrowRightIcon size={14}/></button></div><div className="gl-tools-summary"><button onClick={()=>{navigate('ai');setTool('Codex')}}><span className="gl-provider codex"><OpenAiLogoIcon size={25}/></span><b>Codex</b><div className="gl-meter"><i style={{width:'62%'}}/></div><span>62% 剩余</span><ArrowRightIcon size={14}/></button><button onClick={()=>{navigate('ai');setTool('Claude Code')}}><span className="gl-provider claude"><AsteriskSimpleIcon size={27} weight="bold"/></span><b>Claude</b><div className="gl-tool-reset"><span>{state.quotaRestored?'额度已核验':'14:30 后核验'}</span><small>恢复后续跑 · 不额外付费</small></div><ArrowRightIcon size={14}/></button></div></>}
          {prefs.showQuote&&<div className="gl-quote"><img src={mountains} alt="雪山远景"/><p>好的项目，<br/>是人和 AI 一起，把想法变成现实。</p><span>—</span></div>}
        </>}
        {tab==='projects'&&<><PageTitle title={task?.title??project?.name??'项目'} subtitle={task?'项目 → 任务 → Plan':project?project.goal:'把目标拆成每一步可交付的工作。'} back={taskId?()=>setTaskId(null):projectId?()=>setProjectId(null):undefined} action={<button className="gl-icon" aria-label={taskId?'新建 Plan':projectId?'新建任务':'新建项目'} onClick={()=>setCreate(taskId?'plan':projectId?'task':'project')}><PlusIcon size={24}/></button>}/>
          {!projectId?projects.map(p=>{const ids=tasks.filter(t=>t.projectId===p.id).map(t=>t.id);const plans=state.plans.filter(pl=>ids.includes(pl.taskId));return <button key={p.id} className="gl-project-card" onClick={()=>setProjectId(p.id)}><div className="gl-project-top"><FolderIcon size={30} weight="duotone"/><span>{p.date.slice(5).replace('-',' / ')}</span></div><h2>{p.name}</h2><p>{p.goal}</p><div className="gl-project-bottom"><span>{plans.filter(pl=>pl.status==='accepted').length} / {plans.length} Plan 已验收</span><ArrowRightIcon size={19}/></div></button>}):!taskId?<><button className="gl-secondary gl-project-report" onClick={()=>openReport('projects')}><ChartBarIcon size={19}/>项目报告<ArrowRightIcon size={17}/></button><div className="gl-milestone"><span>版本目标</span><h2>{project?.goal}</h2><p>预计交付 {project?.date}</p></div><div className="gl-section-heading"><h2>目标范围</h2><button onClick={()=>setCreate('task')}>添加任务<PlusIcon size={14}/></button></div>{tasks.filter(t=>t.projectId===projectId).length===0?<Empty title="从一个任务开始" detail="将项目目标拆成可交付的任务。"/>:tasks.filter(t=>t.projectId===projectId).map(t=><button className="gl-task-row" key={t.id} onClick={()=>setTaskId(t.id)}><span className="gl-badge">P{t.priority}</span><div><h3>{t.title}</h3><p>{state.plans.filter(p=>p.taskId===t.id).length} 个 Plan</p></div><ArrowRightIcon size={18}/></button>)}</>:<><div className="gl-info"><GitBranchIcon size={22}/><p>Plan 独立派发与验收，先满足依赖，再按优先级安排。</p></div>{state.plans.filter(p=>p.taskId===taskId).length===0?<Empty title="创建第一个 Plan" detail="明确执行工具、依赖与验收条件。"/>:state.plans.filter(p=>p.taskId===taskId).map((p,i)=><button key={p.id} className="gl-plan-row" onClick={()=>openPlan(p)}><span className={`gl-plan-number ${p.status==='accepted'?'done':''}`}>{p.status==='accepted'?<CheckIcon size={17}/>:String(i+1).padStart(2,'0')}</span><div><h3>{p.title}</h3><p>{p.tool} · P{p.priority}</p><span className={`gl-badge ${p.status}`}>{statusText[p.status]}</span></div><ArrowRightIcon size={16}/></button>)}<button className="gl-secondary" onClick={()=>setCreate('plan')}><PlusIcon size={18}/>添加 Plan</button></>}
        </>}
        {tab==='ai'&&<><PageTitle title="你的 AI" subtitle="每个工具，都有清晰的工作边界。"/><div className="gl-group"><Toggle label="自然恢复后自动续跑" detail="原会话 · 已有订阅 · 不额外付费" checked={prefs.autoResume} change={v=>setPrefs({...prefs,autoResume:v})}/></div><div className="gl-ai-list">{toolRows.map(t=><button key={t.name} className="gl-quota-card" onClick={()=>setTool(t.name)}><div><span className={`gl-provider ${t.name==='Claude Code'?'claude':'codex'}`}><ToolIcon name={t.name}/></span><h2>{t.name}<small>{t.capability}</small></h2><ArrowRightIcon size={17}/></div><div className="gl-quota-value"><b>{t.name==='Claude Code'&&state.quotaRestored?'100':t.remaining??'—'}<small>{t.remaining===null?'':'%'}</small></b><span>{t.name==='Claude Code'&&state.quotaRestored?'短时额度已核验':t.reset}</span></div><div className="gl-meter"><i style={{width:`${t.name==='Claude Code'&&state.quotaRestored?100:t.remaining??0}%`}}/></div><p>{t.name==='Claude Code'&&weekBlocked?'周额度耗尽 · 继续等待':t.detail}</p><small>演示样本 · {t.window} · 14:07 更新</small></button>)}</div><div className="gl-section-heading"><h2>公共重置信号</h2></div><a className="gl-public-signal" href="https://betteropc.com/ai-products/reset-signals" target="_blank" rel="noreferrer"><b>BetterOPC<ArrowRightIcon size={17}/></b><p>公共重置与活动动态</p><small>原型仅提供来源链接，不代表个人额度恢复。</small></a><details className="gl-faq gl-simulation"><summary>演示：额度恢复与周限额</summary><Toggle label="周额度也已耗尽" checked={weekBlocked} change={v=>{setWeekBlocked(v);setState(s=>({...s,quotaRestored:false,plans:s.plans.map(p=>p.id==='p4'&&p.status!=='cancelled'?{...p,status:'waiting'}:p)}))}}/><button className="gl-primary" onClick={simulateQuota}><ArrowsClockwiseIcon size={17}/>模拟到期并核验</button><p>不访问真实账号，也不启动 CLI。</p></details></>}
        {tab==='timeline'&&<><PageTitle title="时间线" subtitle="不同节奏，在这里一起向前。"/><div className="gl-filter-row"><select aria-label="时间线项目" value={timelineProject} onChange={e=>setTimelineProject(e.target.value)}><option value="all">全部项目</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button className="gl-link" onClick={()=>setWeekView(!weekView)}>{weekView?'切换日视图':'切换周视图'}</button></div>{weekView&&<div className="gl-week">{['一','二','三','四','五','六','日'].map((d,i)=><button key={d} aria-pressed={day===14+i} className={day===14+i?'active':''} onClick={()=>setDay(14+i)}><small>{d}</small>{14+i}</button>)}</div>}<div className="gl-section-heading"><h2>9 月 {day} 日</h2><span>固定演示日</span></div><div className="gl-segments">{[{id:'all',name:'全部'},{id:'human',name:'我'},{id:'ai',name:'AI'}].map(l=><button key={l.id} className={timelineLane===l.id?'active':''} onClick={()=>setTimelineLane(l.id)}>{l.name}</button>)}</div>{day!==14?<Empty title="这一天还没有演示记录" detail="选择 9 月 14 日查看人机协作时间线。"/>:<div className="gl-timeline-grid"><div className="gl-timeline-time">{['13:00','13:30','14:08','14:30','15:00'].map(t=><span key={t}>{t}</span>)}</div>{timelineLane!=='ai'&&<div className="gl-timeline-lane"><h3>我</h3>{timelineProject!=='valley'?<><button className="gl-timeline-block human" onClick={()=>setNotice('需求梳理 · 人工投入 25 分钟 · 演示记录')}><UserIcon size={17}/><b>梳理版本范围</b><small>刻迹 · 25m</small></button><button className="gl-timeline-block planned" onClick={()=>openPlan(state.plans.find(p=>p.id==='p3')!)}><CheckCircleIcon size={17}/><b>验收数据模型</b><small>计划 · 14:10</small></button></>:<p className="gl-fine">无人工记录</p>}</div>}{timelineLane!=='human'&&<div className="gl-timeline-lane"><h3>AI 工作</h3>{timelineProject!=='valley'&&<button className="gl-timeline-block ai" onClick={()=>openPlan(state.plans.find(p=>p.id==='p3')!)}><OpenAiLogoIcon size={17}/><b>额度数据模型</b><small>Codex · 35m</small></button>}{timelineProject!=='keji'&&<button className="gl-timeline-block wait" onClick={()=>openPlan(state.plans.find(p=>p.id==='p4')!)}><HourglassIcon size={17}/><b>远程恢复验证</b><small>Claude · {statusText[state.plans.find(p=>p.id==='p4')?.status??'waiting']}</small><small>14:30 后核验</small></button>}</div>}</div>}<div className="gl-info"><ClockIcon size={23}/><p>人工投入 25m · AI 活跃 35m<br/>等待单独记录，不和人工时间相加。</p></div></>}
        {tab==='reports'&&<><PageTitle title={reportProject?`${reportProject.name} · 报告`:'开发报告'} back={closeReport} subtitle="2026.09.14 · Asia/Dubai · 草稿" action={<button className="gl-icon" aria-label="导出日报" onClick={()=>exportData(true)}><DownloadSimpleIcon size={23}/></button>}/><button className="gl-report-hero" onClick={()=>setInfo('score')}><span>今天的交付</span><h2>{reportPlans.filter(p=>p.status==='accepted').length}<small>个 Plan 已验收</small></h2><p>生产力分：样本不足，暂不计算</p><span className="gl-link">查看评分依据<ArrowRightIcon size={16}/></span></button><div className="gl-section-heading"><h2>ChangeLog</h2><span>按验收事实记录</span></div><div className="gl-report-list">{reportPlans.length===0&&<Empty title="暂无项目报告" detail="这个项目还没有 Plan，完成执行和验收后会在这里汇总。"/>}{reportPlans.map(p=><button key={p.id} onClick={()=>openPlan(p)}>{p.status==='accepted'?<CheckCircleIcon weight="duotone"/>:<CircleIcon/>}<div><h3>{p.title}</h3><p>{p.tool} · {statusText[p.status]}</p></div><ArrowRightIcon size={16}/></button>)}</div><button className="gl-secondary" onClick={()=>setInfo('evidence')}><GitBranchIcon size={19}/>查看提交与验收证据</button><div className="gl-section-heading"><h2>下一步建议</h2></div><div className="gl-info"><SparkleIcon size={24}/><p>{reportPlans.some(p=>p.status==='review')?'先确认待验收的结果，再安排后续工作。':reportPlans.some(p=>p.status==='waiting')?'等待工具额度核验，同时安排可并行的人工工作。':reportPlans.length?'检查剩余计划与已验收成果，安排下一步。':'先为项目创建任务与 Plan。'}<br/>等待额度的 Plan 保留原会话。</p></div><p className="gl-fine">全部为示例记录，没有真实 commit 或账单。实际费用未知时不显示“¥0”。</p></>}
        </main>}
      </div>
      {!settings&&<nav className="gl-bottom-nav" aria-label="主导航">{tabs.map(t=><button key={t.id} aria-current={activeTab===t.id?'page':undefined} className={activeTab===t.id?'active':''} onClick={()=>navigate(t.id)}><t.icon size={25} weight={activeTab===t.id?'duotone':'regular'}/><span>{t.title}</span></button>)}</nav>}
      {notice&&<div role="status" className="gl-toast"><CheckCircleIcon size={19}/>{notice}</div>}
      {currentPlan&&<GlassSheet title="Plan 详情" close={()=>setSelected(null)}><span className="gl-eyebrow">{tasks.find(t=>t.id===currentPlan.taskId)?.title} / PLAN</span><h2 className="gl-sheet-title">{currentPlan.title}</h2><div className="gl-plan-meta"><span className="gl-badge">P{currentPlan.priority}</span><span className={`gl-badge ${currentPlan.status}`}>{statusText[currentPlan.status]}</span><span>{currentPlan.tool}</span></div><h3 className="gl-section-label">验收条件</h3><div className="gl-criteria">{currentPlan.criteria.map(c=><label key={c}><input type="checkbox" checked={checks.includes(c)} disabled={currentPlan.status!=='review'} onChange={e=>setChecks(old=>e.target.checked?[...old,c]:old.filter(v=>v!==c))}/>{c}</label>)}</div><button className="gl-link" onClick={()=>{setSelected(null);setInfo('evidence')}}>查看演示证据<ArrowRightIcon size={15}/></button><h3 className="gl-section-label">分派策略</h3><div className="gl-segments">{['均衡','速度优先','节省额度','手动'].map(p=><button key={p} className={policy===p?'active':''} onClick={()=>setPolicy(p)}>{p}</button>)}</div><label className="gl-form">执行工具<select aria-label="Plan 执行工具" disabled={currentPlan.status!=='ready'} value={currentPlan.tool} onChange={e=>{const tool=e.target.value;setPolicy('手动');setState(s=>({...s,plans:s.plans.map(p=>p.id===selected?{...p,tool}:p)}))}}><option>Codex</option><option>Claude Code</option></select></label><div className="gl-info"><ShieldCheckIcon size={21}/><p>{currentPlan.status==='ready'?'演示推荐基于可用工具。启动前仍需校验额度与依赖。':'已有执行上下文，保持原工具与会话。'}<br/>零额外付费 · 无真实 AI 调用</p></div>{currentPlan.depends.length>0&&<p className="gl-fine">依赖：{currentPlan.depends.map(id=>state.plans.find(p=>p.id===id)?.title).join('、')}</p>}
        {currentPlan.status==='review'?<button className="gl-primary" disabled={checks.length!==currentPlan.criteria.length} onClick={()=>act('accept')}><CheckIcon size={18}/>确认验收通过</button>:currentPlan.status==='running'?<button className="gl-primary" onClick={()=>act('finish')}>模拟完成，进入验收</button>:currentPlan.status==='accepted'?<div className="gl-success"><CheckCircleIcon size={24}/>已验收，已计入目标进度</div>:currentPlan.status==='cancelled'?<div className="gl-info">已取消，不会被自动恢复。</div>:<button className="gl-primary" disabled={(currentPlan.status==='waiting'&&!state.quotaRestored)||currentPlan.depends.some(id=>state.plans.find(p=>p.id===id)?.status!=='accepted')} onClick={()=>{if(currentPlan.tool==='Claude Code'&&!state.quotaRestored){setState(s=>({...s,plans:s.plans.map(p=>p.id===selected?{...p,status:'waiting'}:p)}));setSelected(null);setNotice('指定工具额度不足，等待恢复，不转付费执行')}else act('run')}}>{currentPlan.status==='waiting'?<PauseIcon size={18}/>:<PlayIcon size={18}/>} {currentPlan.status==='waiting'&&!state.quotaRestored?'等待额度恢复':'按此安排执行'}</button>}
        {!['accepted','cancelled'].includes(currentPlan.status)&&<button className="gl-danger subtle" onClick={()=>act('cancel')}>取消此 Plan（演示）</button>}
      </GlassSheet>}
      {create&&<GlassSheet title={create==='project'?'新建项目':create==='task'?'新建任务':'新建 Plan'} close={()=>setCreate(null)}><form className="gl-form" onSubmit={createItem}><label>名称<input name="title" required maxLength={60} placeholder={create==='project'?'例如：个人网站':'要交付什么？'}/></label>{create==='project'?<><label>版本目标<input name="goal" required placeholder="例如：本周交付 v1.2"/></label><label>目标日期<input name="date" type="date" defaultValue="2026-09-18" required/></label></>:<label>优先级<select name="priority" defaultValue="1"><option value="0">P0 · 紧急</option><option value="1">P1 · 重要</option><option value="2">P2 · 常规</option><option value="3">P3 · 待安排</option></select></label>}{create==='plan'&&<><label>执行工具<select name="tool"><option>Codex</option><option>Claude Code</option></select></label><label>验收条件<textarea name="criteria" required placeholder="每行一项可验证的结果"/></label><h3>依赖的 Plan</h3>{state.plans.filter(p=>p.taskId===taskId).map(p=><label className="gl-checkbox" key={p.id}><input type="checkbox" name="depends" value={p.id}/>{p.title}</label>)}</>}<button className="gl-primary" type="submit">创建</button><p className="gl-fine">仅保存在本次交互，刷新后重置。</p></form></GlassSheet>}
      {tool&&<GlassSheet title={tool} close={()=>setTool(null)}><div className="gl-tool-detail-symbol"><ToolIcon name={tool}/></div><h2 className="gl-sheet-title">{tool==='Gemini CLI'?'额度与恢复能力待验证':tool==='Cursor'?'记录与提醒，先管理起来':'个人账号 · 订阅额度'}</h2><p className="gl-body-copy">{tool==='Cursor'||tool==='Gemini CLI'?'不会因为显示“已连接”就开放自动派发；每项能力需要单独适配。':'短时和周窗口分别核验。自然恢复后仍检查电脑、会话、授权和计费边界。'}</p><div className="gl-info">来源：演示样本 · 2026-09-14 14:07<br/>这些数值不代表你真实账号的可用额度。</div>{tool==='Claude Code'&&<button className="gl-secondary" onClick={()=>{setTool(null);const p=state.plans.find(p=>p.id==='p4');if(p)openPlan(p)}}>查看等待中的 Plan</button>}<button className="gl-secondary" onClick={()=>{setTool(null);setSettings('root')}}>管理账号与设备</button></GlassSheet>}
      {info&&<GlassSheet title={info==='score'?'评分依据':info==='evidence'?'成果证据':'关于这份设计稿'} close={()=>setInfo(null)}>{info==='score'?<div className="gl-data-map"><h3>先做什么</h3><p>P0–P3 人工优先级在前；组内按目标贡献35%、紧迫度30%、解锁价值20%、等待15%排序。依赖是硬约束。</p><h3>交给谁</h3><p>先检查能力、额度、权限和零付费，再比较等待时间、上下文与历史质量。样本不足不显示虚构成功率。</p><h3>成果怎样</h3><p>目标贡献45%、验收质量30%、计划兑现15%、资源效率10%。按确认范围封顶，不按 Plan 数刷分。覆盖不足时不显示总分。</p></div>:info==='evidence'?<div className="gl-data-map"><CodeIcon size={32}/><h3>{reportProject?`${reportProject.name} · 演示证据说明`:'额度数据模型 · 演示证据'}</h3><p>{reportProject?'项目报告仅汇总当前项目；真实提交和测试证据尚未接入。':'覆盖：未知状态、多个窗口、采样去重。'}</p><p>生产版会关联真实 commit、PR、构建与测试记录。当前没有生成虚构 Git 链接，也没有执行真实测试任务。</p></div>:<><p className="gl-body-copy">当前是可点击的 App 设计稿：支持项目→任务→Plan、验收、额度恢复演示，以及账户与设置流程。</p><div className="gl-info">没有登录真实账号，不发送验证码、不调用真实 AI、不产生费用。请勿输入真实密码或验证码。</div><button className="gl-secondary" onClick={()=>{setInfo(null);setSettings('root')}}>体验个人中心</button></>}</GlassSheet>}
    </div>
  </div>
}
